name: Test Cellranger Version

on:
  push:
    branches:
      - main

jobs:
  test_cellranger_version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Pull Docker image
      run: docker pull ccrsfifx/cellranger:7.2.0
      
    - name: Run container and check cellranger version
      run: docker run --rm ccrsfifx/cellranger:7.2.0 cellranger --version
