name: Test Spaceranger Version

on:
  push:
    branches: [ main ]
    paths:
      - 'dockerhub_repos/spaceranger/v3.0.0/Dockerfile'

jobs:
  test_cellranger_version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Pull Docker image
      run: docker pull ccrsfifx/spaceranger:3.0.0
      
    - name: Run container and check spaceranger version
      run: docker run --rm ccrsfifx/spaceranger:3.0.0 spaceranger --version

    - name: Validate version consistency
      run: |
          # Extract the expected version from the 'spaceranger --version' output
          CELLRANGER_VERSION=$(docker run ccrsfifx/spaceranger:3.0.0 spaceranger --version | awk '{print $2}')

          # Compare with the Docker Hub tag
          if [[ "$CELLRANGER_VERSION" != "spaceranger-3.0.0" ]]; then
            echo "Error: Space Ranger version ($CELLRANGER_VERSION) doesn't match Docker Hub tag (${{ steps.tag-info.outputs.tag }})"
            exit 1
          else
            echo "Space Ranger version matches Docker Hub tag."
          fi
